# Generated by Django 6.0.7 on 2026-08-25 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_booking_total_amount_positive_and_more"),
        ("payments", "0005_alter_payment_payment_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
