# Generated by Django 6.0.7 on 2026-09-07 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_cancelled_at_booking_cancelled_by_and_more"),
        ("payments", "0006_payment_payment_amount_positive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refund",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="refund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("online", "Online Payment"),
                    ("easypaisa", "Easypaisa"),
                    ("raast", "Raast Transfer"),
                ],
                default="bank_transfer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="supporting_document",
            field=models.FileField(blank=True, upload_to="refunds/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="refund",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("processed", "Processed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
    ]
