import { test, expect, request as apiRequest, type APIRequestContext } from '@playwright/test';
import { loginViaApi, type RoleName } from '../helpers/auth';

/**
 * Bookings module — BROWSER (real UI) automation for specs/bookings.md.
 *
 * This spec drives the actual rendered ERP pages with `page` and role-based locators,
 * complementing tests/bookings/bookings.spec.ts (which is heavier on the API/data-plane).
 * Fixtures are created and state is verified through the admin API (`request`), exactly as
 * the data-plane spec does.
 *
 * PREREQUISITES (see tests/fixtures/seed_roles.py and tests/setup/auth.setup.ts):
 *   - Role users (admin / qa_management / qa_accounts / qa_sales / qa_customer) seeded with `admin123`.
 *   - Dev server on http://127.0.0.1:8000 with DJANGO_DEBUG=True (else SECURE_SSL_REDIRECT 301s).
 *   - tests/.auth/*.json generated by the `setup` project.
 *
 * RED markers: `// CONFIRMED BUG: docs/qa/findings-confirmed.md F3` — the booking web views
 * (list/create/detail/edit) are guarded only by `@login_required`, so a portal customer can
 * view/edit any booking. The SEC tests assert the CORRECT behaviour (denial) and stay RED on
 * purpose — do NOT weaken them or mark them fixme.
 *
 * Scenario-ID note: the two create-form price guards (below-cost / under-deposit) and the
 * zero-advance confirm are documented in the spec as BOOK-API-02 / BOOK-API-03; here they are
 * exercised through the real UI form rather than the DRF endpoint.
 */

// Plot fixture values. Charges (development/lease/other) are not writable through any
// API/form/admin surface, so total_cost === price here (see tests/bookings/bookings.spec.ts).
const PRICE = '108000.00';
const TOTAL_COST = '108000.00';
const HOLDING_DEPOSIT = '10000.00';
const ADVANCE = '10000.00';

// ── unique id generation ──────────────────────────────────────────────────────────────
let counter = 0;
function uid(tag: string): string {
  counter += 1;
  return `${Date.now().toString(36)}${Math.floor(Math.random() * 1e8).toString(36)}${counter}${tag}`;
}
function randomDigits(n: number): string {
  let s = '';
  for (let i = 0; i < n; i++) s += Math.floor(Math.random() * 10);
  return s;
}

// ── created-resource tracking for afterAll cleanup ────────────────────────────────────
const created = {
  projects: [] as number[],
  plots: [] as number[],
  customers: [] as number[],
  bookings: [] as number[],
};

function csrf(token: string): Record<string, string> {
  return { 'X-CSRFToken': token };
}

/** Log in via API and return a CSRF token valid for the current session cookie. */
async function apiLogin(req: APIRequestContext, role: RoleName): Promise<string> {
  await loginViaApi(req, role);
  const state = await req.storageState();
  const cookie = state.cookies.find((c) => c.name === 'csrftoken');
  return cookie ? cookie.value : '';
}

// ── fixture helpers (data-plane) ──────────────────────────────────────────────────────
async function createProject(req: APIRequestContext, token: string): Promise<number> {
  const res = await req.post('/api/projects/', {
    data: { name: `QA Proj ${uid('proj')}`, location: 'Karachi' },
    headers: csrf(token),
  });
  expect(res.status(), 'create project').toBe(201);
  const body = await res.json();
  created.projects.push(body.id);
  return body.id;
}

async function createPlot(
  req: APIRequestContext,
  token: string,
  projectId: number,
  opts: { price?: string; holdingDeposit?: string } = {},
): Promise<{ id: number; plotNumber: string }> {
  const plotNumber = `QA-${uid('plot')}`;
  const res = await req.post('/api/plots/', {
    data: {
      plot_number: plotNumber,
      project: projectId,
      size_marla: '5.00',
      price: opts.price ?? PRICE,
      holding_deposit: opts.holdingDeposit ?? HOLDING_DEPOSIT,
      status: 'available',
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create plot').toBe(201);
  const body = await res.json();
  created.plots.push(body.id);
  return { id: body.id, plotNumber };
}

async function createCustomer(req: APIRequestContext, token: string): Promise<number> {
  const d = randomDigits(13);
  const cnic = `${d.slice(0, 5)}-${d.slice(5, 12)}-${d.slice(12)}`;
  const phone = `+92-3${randomDigits(9)}`;
  const res = await req.post('/api/customers/', {
    data: {
      first_name: 'QA',
      last_name: `Buyer-${uid('c')}`,
      email: `qa-${uid('mail')}@example.com`,
      phone,
      cnic,
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create customer').toBe(201);
  // Create serializer omits numeric `id` — resolve it via the list (search by CNIC).
  const list = await (await req.get(`/api/customers/?search=${encodeURIComponent(cnic)}`)).json();
  const row = list.find((c: any) => c.cnic === cnic);
  expect(row, 'created customer resolvable by cnic').toBeTruthy();
  created.customers.push(row.id);
  return row.id;
}

interface BaseFixture {
  projectId: number;
  plotId: number;
  plotNumber: string;
  customerId: number;
}

async function createBaseFixture(
  req: APIRequestContext,
  token: string,
  opts: { price?: string; holdingDeposit?: string } = {},
): Promise<BaseFixture> {
  const projectId = await createProject(req, token);
  const plot = await createPlot(req, token, projectId, opts);
  const customerId = await createCustomer(req, token);
  return { projectId, plotId: plot.id, plotNumber: plot.plotNumber, customerId };
}

/** POST /api/bookings/ then look the created booking up by plot_number (create serializer omits id). */
async function createBookingViaApi(
  req: APIRequestContext,
  token: string,
  f: BaseFixture,
  opts: { totalAmount?: string; advance?: string; notes?: string } = {},
): Promise<any> {
  const totalAmount = opts.totalAmount ?? TOTAL_COST;
  const advance = opts.advance ?? ADVANCE;
  const res = await req.post('/api/bookings/', {
    data: {
      customer: f.customerId,
      plot: f.plotId,
      total_amount: totalAmount,
      advance_paid: advance,
      source: 'walk_in',
      notes: opts.notes ?? '',
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create booking via API').toBe(201);
  const list = (await (await req.get(`/api/bookings/?project=${f.projectId}`)).json()) as any[];
  const booking = list.find((b) => b.plot_number === f.plotNumber);
  expect(booking, 'booking found by plot_number').toBeTruthy();
  created.bookings.push(booking.id);
  return booking;
}

async function getBooking(req: APIRequestContext, id: number): Promise<any> {
  const res = await req.get(`/api/bookings/${id}/`);
  expect(res.status(), 'get booking').toBe(200);
  return res.json();
}

async function getPlot(req: APIRequestContext, id: number): Promise<any> {
  const res = await req.get(`/api/plots/${id}/`);
  expect(res.status(), 'get plot').toBe(200);
  return res.json();
}

async function getPayments(req: APIRequestContext, bookingId: number): Promise<any[]> {
  const res = await req.get(`/api/payments/?booking=${bookingId}`);
  expect(res.status(), 'get payments').toBe(200);
  return res.json();
}

async function reversePayment(req: APIRequestContext, token: string, paymentId: number): Promise<void> {
  await req.post(`/payments/${paymentId}/reverse/`, { form: {}, headers: csrf(token) });
}

async function cancelBookingWeb(
  req: APIRequestContext,
  token: string,
  bookingId: number,
  reason = 'customer_request',
): Promise<void> {
  await req.post(`/bookings/${bookingId}/cancel/`, {
    form: { reason, notes: '' },
    headers: csrf(token),
  });
}

async function cleanupAll(): Promise<void> {
  const ctx = await apiRequest.newContext({ baseURL: 'http://127.0.0.1:8000' });
  try {
    const token = await apiLogin(ctx, 'admin');
    for (const bid of created.bookings) {
      try {
        const pr = await ctx.get(`/api/payments/?booking=${bid}`);
        if (pr.ok()) {
          const pays = (await pr.json()) as any[];
          for (const p of pays) {
            if (p.status === 'verified') {
              await ctx.post(`/payments/${p.id}/reverse/`, { form: {}, headers: csrf(token) }).catch(() => {});
            }
          }
        }
      } catch {
        /* best effort */
      }
      await ctx.delete(`/api/bookings/${bid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const pid of created.plots) {
      await ctx.delete(`/api/plots/${pid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const cid of created.customers) {
      await ctx.delete(`/api/customers/${cid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const pid of created.projects) {
      await ctx.delete(`/api/projects/${pid}/`, { headers: csrf(token) }).catch(() => {});
    }
  } finally {
    await ctx.dispose();
  }
}

test.afterAll(cleanupAll);

// ═══════════════════════════════════════════════════════════════════════════════════
// HP — happy path (admin drives the real UI)
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('HP — happy path', () => {
  test.beforeEach(async ({ page }) => { await loginViaApi(page.request, 'admin'); });

  test('BOOK-HP-01 — Create booking: auto BKG id, plot booked, verified Payment + Receipt', async ({
    page,
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);

    await page.goto('/bookings/create/');
    await expect(page.getByRole('heading', { name: 'Create New Booking' })).toBeVisible();
    // The plot must appear in the available-plots dropdown.
    await expect(page.locator('select[name="plot"]').locator('option', { hasText: f.plotNumber })).toBeAttached();

    await page.locator('select[name="customer"]').selectOption(String(f.customerId));
    await page.locator('select[name="plot"]').selectOption(String(f.plotId));
    await page.getByLabel('Total amount').fill(TOTAL_COST);
    await page.getByLabel('Advance paid').fill(ADVANCE);
    await page.getByRole('button', { name: 'Create Booking' }).click();
    await expect(page).toHaveURL(/\/bookings\/$/);

    const booking = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[]).find(
      (b) => b.plot_number === f.plotNumber,
    );
    expect(booking).toBeTruthy();
    created.bookings.push(booking.id);

    // Exact money (DRF Decimal strings) + auto-generated id format.
    expect(booking.booking_id).toMatch(/^BKG-\d{5}$/);
    expect(booking.status).toBe('pending');
    expect(booking.total_amount).toBe(TOTAL_COST);
    expect(booking.advance_paid).toBe(ADVANCE);

    // The auto BKG id is shown on the bookings list.
    await expect(page.getByRole('link', { name: booking.booking_id })).toBeVisible();

    expect((await getPlot(request, f.plotId)).status).toBe('booked');

    const pays = await getPayments(request, booking.id);
    const verified = pays.filter((p) => p.status === 'verified');
    expect(verified.length).toBe(1);
    expect(verified[0].amount).toBe(ADVANCE);
    const receipts = await (await request.get(`/api/receipts/?payment=${verified[0].id}`)).json();
    expect(receipts.length).toBe(1);
  });

  test('BOOK-HP-02 — Confirm booking: pending → confirmed', async ({ page, request }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    await page.goto(`/bookings/${booking.id}/confirm/`);
    await page.getByRole('button', { name: /Yes, Confirm Booking/ }).click();
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

    expect((await getBooking(request, booking.id)).status).toBe('confirmed');
    await expect(page.getByText('Confirmed', { exact: true }).first()).toBeVisible();
  });

  test('BOOK-HP-03 — Edit booking: valid edit persists; under-cost / under-deposit rejected', async ({
    page,
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    // Valid edit.
    await page.goto(`/bookings/${booking.id}/edit/`);
    await page.getByLabel('Total amount').fill('110000.00');
    await page.getByLabel('Advance paid').fill('12000.00');
    await page.getByRole('button', { name: 'Update' }).click();
    await expect(page).toHaveURL(/\/bookings\/$/);

    let b = await getBooking(request, booking.id);
    expect(b.total_amount).toBe('110000.00');
    expect(b.advance_paid).toBe('12000.00');
    expect((await getPlot(request, f.plotId)).status).toBe('booked');

    // Under-cost edit must be rejected (form re-renders, values unchanged).
    await page.goto(`/bookings/${booking.id}/edit/`);
    await page.getByLabel('Total amount').fill('107000.00');
    await page.getByLabel('Advance paid').fill('12000.00');
    await page.getByRole('button', { name: 'Update' }).click();
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/edit/$`));
    await expect(page.getByText('Please correct the errors below.')).toBeVisible();
    b = await getBooking(request, booking.id);
    expect(b.total_amount).toBe('110000.00');

    // Under-deposit edit must be rejected.
    await page.goto(`/bookings/${booking.id}/edit/`);
    await page.getByLabel('Total amount').fill('110000.00');
    await page.getByLabel('Advance paid').fill('5000.00');
    await page.getByRole('button', { name: 'Update' }).click();
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/edit/$`));
    await expect(page.getByText('Please correct the errors below.')).toBeVisible();
    b = await getBooking(request, booking.id);
    expect(b.advance_paid).toBe('12000.00');
  });

  test('BOOK-HP-04 — Booking detail renders customer/plot/amounts/notes', async ({ page, request }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const note = `QA note ${uid('n')}`;
    const booking = await createBookingViaApi(request, token, f, { notes: note });
    const cust = await (await request.get(`/api/customers/${f.customerId}/`)).json();

    await page.goto(`/bookings/${booking.id}/`);

    await expect(page.getByText(booking.booking_id).first()).toBeVisible();
    await expect(page.getByText(cust.full_name)).toBeVisible();
    await expect(page.getByText(f.plotNumber)).toBeVisible();
    await expect(page.getByText('Total Amount', { exact: true })).toBeVisible();
    await expect(page.getByText('Advance Paid', { exact: true })).toBeVisible();
    await expect(page.getByText('Remaining Balance', { exact: true })).toBeVisible();
    await expect(page.getByText('Pending', { exact: true }).first()).toBeVisible();
    await expect(page.getByText(note)).toBeVisible();
  });

  test('BOOK-HP-05 — Cancel blocked while verified payments exist; releases plot after reversal', async ({
    page,
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    // Blocked while the verified advance payment exists: the view bounces back to detail.
    await page.goto(`/bookings/${booking.id}/cancel/`);
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));
    expect((await getBooking(request, booking.id)).status).toBe('pending');
    expect((await getPlot(request, f.plotId)).status).toBe('booked');

    // Reverse the advance payment, then cancel for real.
    const pays = await getPayments(request, booking.id);
    const verified = pays.find((p) => p.status === 'verified');
    expect(verified).toBeTruthy();
    await reversePayment(request, token, verified!.id);

    await page.goto(`/bookings/${booking.id}/cancel/`);
    await page.getByRole('button', { name: /Confirm Cancellation/ }).click();
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

    expect((await getBooking(request, booking.id)).status).toBe('cancelled');
    expect((await getPlot(request, f.plotId)).status).toBe('available');
  });

  test('BOOK-HP-06 — Reopen cancelled booking: pending + plot re-reserved', async ({ page, request }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const verified = (await getPayments(request, booking.id)).find((p) => p.status === 'verified');
    expect(verified).toBeTruthy();
    await reversePayment(request, token, verified!.id);
    await cancelBookingWeb(request, token, booking.id);
    expect((await getBooking(request, booking.id)).status).toBe('cancelled');

    await page.goto(`/bookings/${booking.id}/reopen/`);
    await page.getByRole('button', { name: /Reopen Booking/ }).click();
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

    expect((await getBooking(request, booking.id)).status).toBe('pending');
    expect((await getPlot(request, f.plotId)).status).toBe('reserved');
  });

  test('BOOK-HP-11 — Invoice PDF renders for finance-or-above', async ({ page, request }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    await page.goto(`/bookings/${booking.id}/`);
    await expect(page.getByRole('link', { name: /Download Invoice/ })).toBeVisible();

    // Fetch through the browser context (admin cookies) and assert it is a real PDF.
    const res = await page.request.get(`/bookings/${booking.id}/invoice/`);
    expect(res.status()).toBe(200);
    expect(res.headers()['content-type']).toContain('application/pdf');
    expect((await res.body()).toString('utf8').startsWith('%PDF')).toBeTruthy();
  });
});

// ═══════════════════════════════════════════════════════════════════════════════════
// EC — edge cases / boundaries (form guards exercised through the real UI)
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('EC — edge cases / boundaries', () => {
  test.beforeEach(async ({ page }) => { await loginViaApi(page.request, 'admin'); });

  test('BOOK-API-02 — Create form rejects total below plot total cost and advance below holding deposit', async ({
    page,
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);

    // Below total cost.
    await page.goto('/bookings/create/');
    await page.locator('select[name="customer"]').selectOption(String(f.customerId));
    await page.locator('select[name="plot"]').selectOption(String(f.plotId));
    await page.getByLabel('Total amount').fill('107000.00');
    await page.getByLabel('Advance paid').fill(ADVANCE);
    await page.getByRole('button', { name: 'Create Booking' }).click();
    await expect(page).toHaveURL(/\/bookings\/create\/$/);
    await expect(page.getByText('Please correct the errors below.')).toBeVisible();

    // Below holding deposit.
    await page.getByLabel('Total amount').fill(TOTAL_COST);
    await page.getByLabel('Advance paid').fill('5000.00');
    await page.getByRole('button', { name: 'Create Booking' }).click();
    await expect(page).toHaveURL(/\/bookings\/create\/$/);
    await expect(page.getByText('Please correct the errors below.')).toBeVisible();

    // No booking was created — the plot is still available.
    expect((await getPlot(request, f.plotId)).status).toBe('available');
    const bookings = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[]).filter(
      (b) => b.plot_number === f.plotNumber,
    );
    expect(bookings.length).toBe(0);
  });

  test('BOOK-API-03 — Confirm with zero advance rejected', async ({ page, request }) => {
    const token = await apiLogin(request, 'admin');
    // holding_deposit = 0 lets us create a zero-advance booking via API.
    const f = await createBaseFixture(request, token, { holdingDeposit: '0' });
    const booking = await createBookingViaApi(request, token, f, { advance: '0' });

    await page.goto(`/bookings/${booking.id}/confirm/`);
    // The view refuses even a GET and bounces back to detail with an error toast.
    await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));
    await expect(page.getByText(/no advance payment/)).toBeVisible();
    expect((await getBooking(request, booking.id)).status).toBe('pending');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════════
// SEC — negative & security (portal customer must not reach another booking)
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('SEC — negative & security', () => {
  test.describe('customer portal user', () => {
    test.beforeEach(async ({ page }) => { await loginViaApi(page.request, 'customer'); });

    test('BOOK-SEC-02 — IDOR: customer cannot view another booking detail', async ({ page, request }) => {
      // CONFIRMED BUG: docs/qa/findings-confirmed.md F3 — booking_detail_view is @login_required only.
      const token = await apiLogin(request, 'admin');
      const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token), {
        notes: `PII note ${uid('pii')}`,
      });

      await page.goto(`/bookings/${booking.id}/`);
      // Correct: denied → redirected away; amounts/notes must never render.
      await expect(page).not.toHaveURL(new RegExp(`/bookings/${booking.id}/$`));
      await expect(page.getByText('Advance Paid', { exact: true })).not.toBeVisible();
      await expect(page.getByText(/PII note/)).not.toBeVisible();
    });

    test('BOOK-SEC-03 — IDOR: customer cannot edit another booking amounts', async ({ page, request }) => {
      // CONFIRMED BUG: docs/qa/findings-confirmed.md F3 — booking_edit_view is @login_required only.
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      await page.goto(`/bookings/${booking.id}/edit/`);
      // Correct: denied → redirected away; the edit form must never render.
      await expect(page).not.toHaveURL(new RegExp(`/bookings/${booking.id}/edit/$`));
      await expect(page.getByLabel('Total amount')).not.toBeVisible();
    });
  });
});
