# Generated by Django 6.0.7 on 2026-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_lead_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Enquiry"),
                    ("strip", "Launch Strip"),
                    ("newsletter", "Newsletter Subscribe"),
                ],
                default="hero",
                max_length=20,
            ),
        ),
    ]
