# Generated by Django 6.0.7 on 2026-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_agent_companysettings_leadnote_lead_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("management", "Management"),
                    ("accounts", "Accounts"),
                    ("sales", "Sales"),
                    ("hr", "HR"),
                    ("project_manager", "Project Manager"),
                    ("contractor", "Contractor"),
                    ("staff", "Staff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("management", "Management"),
                    ("accounts", "Accounts"),
                    ("sales", "Sales"),
                    ("hr", "HR"),
                    ("project_manager", "Project Manager"),
                    ("contractor", "Contractor"),
                    ("staff", "Staff"),
                ],
                default="sales",
                max_length=20,
            ),
        ),
    ]
