# Generated by Django 6.0.7 on 2026-08-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_approvalstep_role_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="ai_language",
            field=models.CharField(
                choices=[("english", "English"), ("roman_urdu", "Roman Urdu")],
                default="english",
                help_text="Global language for AI assistant replies (English or Roman Urdu).",
                max_length=20,
            ),
        ),
    ]
