# Generated by Django 6.0.7 on 2026-08-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Money In"), ("out", "Money Out")],
                        default="out",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("office_expense", "Office Expense"),
                            ("project_cost", "Project Cost"),
                            ("contractor_payment", "Contractor Payment"),
                            ("payroll", "Payroll"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_type"],
                        name="finance_acc_transac_640196_idx",
                    ),
                    models.Index(fields=["date"], name="finance_acc_date_94d197_idx"),
                    models.Index(
                        fields=["direction"], name="finance_acc_directi_a13bde_idx"
                    ),
                ],
            },
        ),
    ]
