# Generated by Django 6.0.7 on 2026-08-25 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_expensecategory_office_accounttransaction_project_and_more"),
        ("hr", "0001_initial"),
        ("properties", "0004_projectmilestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accounttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="account_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="officeexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="office_expense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_budget__gte", 0)),
                name="project_budget_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="project_cost_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectinvestment",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_investment__gte", 0)),
                name="project_investment_non_negative",
            ),
        ),
    ]
