# Generated by Django 6.0.7 on 2026-09-07 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_accounttransaction_account_transaction_amount_positive_and_more",
        ),
        ("hr", "0003_remove_attendance_check_in_and_more"),
        ("properties", "0006_plot_development_charge_plot_lease_charge_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accounttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_id__isnull", False)),
                fields=("reference_type", "reference_id"),
                name="account_transaction_reference_unique",
            ),
        ),
    ]
