# Generated by Django 6.0.7 on 2026-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_accounttransaction_account_transaction_reference_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
