# Generated by Django 6.0.7 on 2026-09-18 13:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_projectcost_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("debit", "Debit Normal"),
                            ("credit", "Credit Normal"),
                        ],
                        default="debit",
                        max_length=10,
                    ),
                ),
                ("is_leaf", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="finance.accounthead",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("CR", "Cash Receipt"),
                            ("CP", "Cash Payment"),
                            ("BR", "Bank Receipt"),
                            ("BP", "Bank Payment"),
                            ("JV", "Journal Voucher"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date", models.DateField()),
                ("narration", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("posted", "Posted")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_reason", models.TextField(blank=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocked_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("narration", models.CharField(blank=True, max_length=255)),
                (
                    "account_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_lines",
                        to="finance.accounthead",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="voucher",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_id__isnull", False)),
                fields=("reference_type", "reference_id"),
                name="voucher_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit__gt", 0), ("credit", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="voucher_line_single_side_nonzero",
            ),
        ),
    ]
