# Generated by Django 6.0.7 on 2026-09-07 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_expense_amount_positive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Cheque No. / Bank Reference / Transaction ID for this expense.",
                max_length=100,
                verbose_name="Payment Reference / Cheque No.",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload a scanned receipt, bill, or invoice as proof.",
                null=True,
                upload_to="expenses/receipts/",
                verbose_name="Receipt / Bill Attachment",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
    ]
