# Generated by Django 6.0.7 on 2026-09-13 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expense_approved_at_expense_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="receipt_attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload a scanned receipt, bill, or invoice as proof.",
                null=True,
                upload_to="expenses/receipts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "png", "jpg", "jpeg", "gif", "webp"]
                    )
                ],
                verbose_name="Receipt / Bill Attachment",
            ),
        ),
    ]
