# Generated by Django 6.0.7 on 2026-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_expense_receipt_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("online", "Online"),
                ],
                default="cash",
                help_text="Determines the Cash/Bank ledger head the expense posts against.",
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
    ]
