# Generated by Django 6.0.7 on 2026-08-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employeesalary",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="employee_salary_amount_non_negative",
            ),
        ),
    ]
