# Generated by Django 6.0.7 on 2026-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_employeesalary_employee_salary_amount_non_negative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="check_out",
        ),
    ]
