# Generated by Django 6.0.7 on 2026-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_projectmilestone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="google_maps_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="project",
            name="longitude",
        ),
    ]
