# Generated by Django 6.0.7 on 2026-09-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_remove_project_google_maps_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="development_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Development/infrastructure charge payable by the buyer",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Lease/registration charge payable by the buyer",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Other one-off plot charges (e.g. documentation)",
                max_digits=15,
            ),
        ),
    ]
