# Generated by Django 6.0.7 on 2026-09-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_plot_development_charge_plot_lease_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmilestone",
            name="completion_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Completion % (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("construction", "Construction"),
                    ("payment", "Payment"),
                    ("development", "Development"),
                    ("documentation", "Documentation"),
                    ("handover", "Handover"),
                    ("other", "Other"),
                ],
                default="construction",
                help_text="Category of this milestone",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="progress_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last progress/completion update",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Planned start date", null=True
            ),
        ),
    ]
