import { test, expect, request as apiRequest, type APIRequestContext } from '@playwright/test';
import { loginViaApi, type RoleName } from '../helpers/auth';

/**
 * Bookings module — full lifecycle + security + API contract (specs/bookings.md).
 *
 * PREREQUISITES (see tests/fixtures/seed_roles.py):
 *   - Role users (qa_management/qa_accounts/qa_sales/qa_customer) seeded with `admin123`.
 *   - Dev server on http://127.0.0.1:8000 with DJANGO_DEBUG=True (else SECURE_SSL_REDIRECT 301s).
 *   - `tests/.auth/*.json` generated by the `setup` project (auth.setup.ts).
 *
 * NOTE: this suite performs many DB writes against the SQLite dev server; if you see
 * intermittent "database is locked", run with `--workers=1`.
 *
 * RED markers: `// CONFIRMED BUG: docs/qa/findings-confirmed.md F5/F3` for the confirmed
 * findings; `// BUG (spec §...):` for spec-documented defects not yet in findings-confirmed.md.
 */

const BASE = 'http://127.0.0.1:8000';

// Plot fixture values (charges are not writable via any API/form/admin surface, so
// total_cost === price here; the booking price-guard invariants are identical).
const PRICE = '108000.00';
const TOTAL_COST = '108000.00';
const HOLDING_DEPOSIT = '10000.00';
const ADVANCE = '10000.00';

// ── id generation ────────────────────────────────────────────────────────────────
let counter = 0;
function uid(tag: string): string {
  counter += 1;
  return `${Date.now().toString(36)}${Math.floor(Math.random() * 1e8).toString(36)}${counter}${tag}`;
}
function randomDigits(n: number): string {
  let s = '';
  for (let i = 0; i < n; i++) s += Math.floor(Math.random() * 10);
  return s;
}

// ── created-resource tracking for afterAll cleanup ────────────────────────────────
const created = {
  projects: [] as number[],
  plots: [] as number[],
  customers: [] as number[],
  bookings: [] as number[],
  templates: [] as number[],
  reservations: [] as number[],
};

function csrf(token: string): Record<string, string> {
  return { 'X-CSRFToken': token };
}

/**
 * Log in via API and return a CSRF token valid for the *current* session cookie.
 * loginViaApi returns the pre-login token, but Django rotates CSRF on login — re-read
 * the cookie jar after login so subsequent unsafe requests pass CSRF.
 */
async function apiLogin(req: APIRequestContext, role: RoleName): Promise<string> {
  await loginViaApi(req, role);
  const state = await req.storageState();
  const cookie = state.cookies.find((c) => c.name === 'csrftoken');
  return cookie ? cookie.value : '';
}

// ── fixture helpers (data-plane) ──────────────────────────────────────────────────
async function createProject(req: APIRequestContext, token: string): Promise<number> {
  const res = await req.post('/api/projects/', {
    data: { name: `QA Proj ${uid('proj')}`, location: 'Karachi' },
    headers: csrf(token),
  });
  expect(res.status(), 'create project').toBe(201);
  const body = await res.json();
  created.projects.push(body.id);
  return body.id;
}

async function createPlot(
  req: APIRequestContext,
  token: string,
  projectId: number,
  opts: { price?: string; holdingDeposit?: string } = {},
): Promise<{ id: number; plotNumber: string }> {
  const plotNumber = `QA-${uid('plot')}`;
  const res = await req.post('/api/plots/', {
    data: {
      plot_number: plotNumber,
      project: projectId,
      size_marla: '5.00',
      price: opts.price ?? PRICE,
      holding_deposit: opts.holdingDeposit ?? HOLDING_DEPOSIT,
      status: 'available',
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create plot').toBe(201);
  const body = await res.json();
  created.plots.push(body.id);
  return { id: body.id, plotNumber };
}

async function createCustomer(req: APIRequestContext, token: string): Promise<number> {
  const d = randomDigits(13);
  const cnic = `${d.slice(0, 5)}-${d.slice(5, 12)}-${d.slice(12)}`;
  const phone = `+92-3${randomDigits(9)}`;
  const res = await req.post('/api/customers/', {
    data: {
      first_name: 'QA',
      last_name: `Buyer-${uid('c')}`,
      email: `qa-${uid('mail')}@example.com`,
      phone,
      cnic,
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create customer').toBe(201);
  const body = await res.json();
  created.customers.push(body.id);
  return body.id;
}

interface BaseFixture {
  projectId: number;
  plotId: number;
  plotNumber: string;
  customerId: number;
}

async function createBaseFixture(
  req: APIRequestContext,
  token: string,
  opts: { price?: string; holdingDeposit?: string } = {},
): Promise<BaseFixture> {
  const projectId = await createProject(req, token);
  const plot = await createPlot(req, token, projectId, opts);
  const customerId = await createCustomer(req, token);
  return { projectId, plotId: plot.id, plotNumber: plot.plotNumber, customerId };
}

/** POST /api/bookings/ then look the created booking up by plot_number (create serializer omits id). */
async function createBookingViaApi(
  req: APIRequestContext,
  token: string,
  f: BaseFixture,
  opts: { totalAmount?: string; advance?: string; notes?: string; source?: string } = {},
): Promise<any> {
  const totalAmount = opts.totalAmount ?? TOTAL_COST;
  const advance = opts.advance ?? ADVANCE;
  const res = await req.post('/api/bookings/', {
    data: {
      customer: f.customerId,
      plot: f.plotId,
      total_amount: totalAmount,
      advance_paid: advance,
      source: opts.source ?? 'walk_in',
      notes: opts.notes ?? '',
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create booking via API').toBe(201);
  const list = await (await req.get(`/api/bookings/?project=${f.projectId}`)).json();
  const booking = (list as any[]).find((b) => b.plot_number === f.plotNumber);
  expect(booking, 'booking found by plot_number').toBeTruthy();
  created.bookings.push(booking.id);
  return booking;
}

async function getBooking(req: APIRequestContext, id: number): Promise<any> {
  const res = await req.get(`/api/bookings/${id}/`);
  expect(res.status(), 'get booking').toBe(200);
  return res.json();
}

async function getPlot(req: APIRequestContext, id: number): Promise<any> {
  const res = await req.get(`/api/plots/${id}/`);
  expect(res.status(), 'get plot').toBe(200);
  return res.json();
}

async function getPayments(req: APIRequestContext, bookingId: number): Promise<any[]> {
  const res = await req.get(`/api/payments/?booking=${bookingId}`);
  expect(res.status(), 'get payments').toBe(200);
  return res.json();
}

async function reversePayment(req: APIRequestContext, token: string, paymentId: number): Promise<void> {
  await req.post(`/payments/${paymentId}/reverse/`, { form: {}, headers: csrf(token) });
}

async function cancelBookingWeb(
  req: APIRequestContext,
  token: string,
  bookingId: number,
  reason = 'customer_request',
): Promise<void> {
  await req.post(`/bookings/${bookingId}/cancel/`, {
    form: { reason, notes: '' },
    headers: csrf(token),
  });
}

async function createBalloonTemplate(req: APIRequestContext, token: string, projectId: number): Promise<number> {
  const res = await req.post('/api/installment-plan-templates/', {
    data: {
      name: `Balloon ${uid('tpl')}`,
      project: projectId,
      total_installments: 12,
      frequency: 'monthly',
      has_balloon_payment: true,
      balloon_installment_number: 12,
      balloon_multiplier: '1.50',
    },
    headers: csrf(token),
  });
  expect(res.status(), 'create balloon template').toBe(201);
  const body = await res.json();
  created.templates.push(body.id);
  return body.id;
}

/** Find a plan by booking id from the (unpaginated) plans list. */
async function getPlanByBooking(req: APIRequestContext, bookingId: number): Promise<any> {
  const list = await (await req.get('/api/installment-plans/')).json();
  return (list as any[]).find((p) => p.booking === bookingId);
}

async function cleanupAll(): Promise<void> {
  const ctx = await apiRequest.newContext({ baseURL: BASE });
  try {
    const token = await apiLogin(ctx, 'admin');
    for (const rid of created.reservations) {
      await ctx.delete(`/api/reservations/${rid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const bid of created.bookings) {
      try {
        const pr = await ctx.get(`/api/payments/?booking=${bid}`);
        if (pr.ok()) {
          const pays = (await pr.json()) as any[];
          for (const p of pays) {
            if (p.status === 'verified') {
              await ctx.post(`/payments/${p.id}/reverse/`, { form: {}, headers: csrf(token) }).catch(() => {});
            }
          }
        }
      } catch {
        /* best effort */
      }
      await ctx.delete(`/api/bookings/${bid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const pid of created.plots) {
      await ctx.delete(`/api/plots/${pid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const tid of created.templates) {
      await ctx.delete(`/api/installment-plan-templates/${tid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const cid of created.customers) {
      await ctx.delete(`/api/customers/${cid}/`, { headers: csrf(token) }).catch(() => {});
    }
    for (const pid of created.projects) {
      await ctx.delete(`/api/projects/${pid}/`, { headers: csrf(token) }).catch(() => {});
    }
  } finally {
    await ctx.dispose();
  }
}

test.afterAll(cleanupAll);

// ═══════════════════════════════════════════════════════════════════════════════════
// HP — happy path
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('HP — happy path', () => {
  test.describe('booking lifecycle (admin/management UI)', () => {
    test.use({ storageState: 'tests/.auth/admin.json' });

    test('BOOK-HP-01 — Create booking: auto BKG id, plot booked, verified Payment + Receipt, advance_paid set', async ({
      page,
      request,
    }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);

      await page.goto('/bookings/create/');
      // Plot must appear in the available-plots dropdown.
      await expect(page.getByLabel('Plot').locator('option', { hasText: f.plotNumber })).toBeAttached();

      await page.getByLabel('Customer').selectOption(String(f.customerId));
      await page.getByLabel('Plot').selectOption(String(f.plotId));
      await page.getByLabel('Total amount').fill(TOTAL_COST);
      await page.getByLabel('Advance paid').fill(ADVANCE);
      await page.getByRole('button', { name: 'Create Booking' }).click();
      await expect(page).toHaveURL(/\/bookings\/$/);

      const booking = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[])
        .find((b) => b.plot_number === f.plotNumber);
      expect(booking).toBeTruthy();
      expect(booking.booking_id).toMatch(/^BKG-\d{5}$/);
      expect(booking.status).toBe('pending');
      expect(booking.total_amount).toBe(TOTAL_COST);
      expect(booking.advance_paid).toBe(ADVANCE);

      const plot = await getPlot(request, f.plotId);
      expect(plot.status).toBe('booked');

      const pays = await getPayments(request, booking.id);
      const verified = pays.filter((p) => p.status === 'verified');
      expect(verified.length).toBe(1);
      expect(verified[0].amount).toBe(ADVANCE);
      const receipts = await (await request.get(`/api/receipts/?payment=${verified[0].id}`)).json();
      expect(receipts.length).toBe(1);

      const audit = await (await request.get('/api/audit-logs/?action=create&model=Booking')).json() as any[];
      expect(audit.some((a) => a.object_id === booking.booking_id)).toBeTruthy();
      // NotificationLog has no API surface — send is failure-safe; existence not asserted here.
    });

    test('BOOK-HP-04 — Booking detail renders customer/plot/amounts/notes', async ({ page, request }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const note = `QA note ${uid('n')}`;
      const booking = await createBookingViaApi(request, token, f, { notes: note });
      const cust = await (await request.get(`/api/customers/${f.customerId}/`)).json();

      await page.goto(`/bookings/${booking.id}/`);

      await expect(page.getByText(booking.booking_id).first()).toBeVisible();
      await expect(page.getByText(cust.full_name)).toBeVisible();
      await expect(page.getByText(cust.phone)).toBeVisible();
      await expect(page.getByText(f.plotNumber)).toBeVisible();
      await expect(page.getByText('Total Amount', { exact: true })).toBeVisible();
      await expect(page.getByText('Advance Paid', { exact: true })).toBeVisible();
      await expect(page.getByText('Remaining Balance', { exact: true })).toBeVisible();
      await expect(page.getByText('Pending', { exact: true }).first()).toBeVisible();
      await expect(page.getByText(note)).toBeVisible();
    });

    test('BOOK-HP-09 — Installment plan auto-generate: balloon applied via web template', async ({ page, request }) => {
      const token = await apiLogin(request, 'admin');
      const projectId = await createProject(request, token);
      const plot = await createPlot(request, token, projectId, { price: '22000.00', holdingDeposit: '10000.00' });
      const customerId = await createCustomer(request, token);
      const templateId = await createBalloonTemplate(request, token, projectId);

      await page.goto('/bookings/create/');
      await page.getByLabel('Customer').selectOption(String(customerId));
      await page.getByLabel('Plot').selectOption(String(plot.id));
      await page.getByLabel('Total amount').fill('22000.00');
      await page.getByLabel('Advance paid').fill('10000.00');
      await page.locator('#installment_template').selectOption(String(templateId));
      await page.getByRole('button', { name: 'Create Booking' }).click();
      await expect(page).toHaveURL(/\/bookings\/$/);

      const booking = (await (await request.get(`/api/bookings/?project=${projectId}`)).json() as any[])
        .find((b) => b.plot_number === plot.plotNumber);
      expect(booking).toBeTruthy();
      created.bookings.push(booking.id);

      const plan = await getPlanByBooking(request, booking.id);
      expect(plan).toBeTruthy();
      expect(plan.installments.length).toBe(12);
      // base = (22000 - 10000)/12 = 1000.00; balloon #12 = 1000.00 * 1.5 = 1500.00 (exact).
      expect(plan.installments[0].amount).toBe('1000.00');
      expect(plan.installments[11].amount).toBe('1500.00');
    });
  });

  test.describe('management-only actions', () => {
    test.use({ storageState: 'tests/.auth/management.json' });

    test('BOOK-HP-02 — Confirm booking requires advance_paid > 0 and transitions pending→confirmed', async ({
      page,
      request,
    }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      await page.goto(`/bookings/${booking.id}/confirm/`);
      await page.getByRole('button', { name: /Yes, Confirm Booking/ }).click();
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

      const b = await getBooking(request, booking.id);
      expect(b.status).toBe('confirmed');
      const audit = await (await request.get('/api/audit-logs/?action=update&model=Booking')).json() as any[];
      expect(audit.some((a) => a.object_id === booking.booking_id)).toBeTruthy();
    });

    test('BOOK-HP-03 — Edit booking: price guards re-applied, plot/status preserved', async ({ page, request }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      // Valid edit.
      await page.goto(`/bookings/${booking.id}/edit/`);
      await page.getByLabel('Total amount').fill('110000.00');
      await page.getByLabel('Advance paid').fill('12000.00');
      await page.getByRole('button', { name: 'Update' }).click();
      await expect(page).toHaveURL(/\/bookings\/$/);

      let b = await getBooking(request, booking.id);
      expect(b.total_amount).toBe('110000.00');
      expect(b.advance_paid).toBe('12000.00');
      expect((await getPlot(request, f.plotId)).status).toBe('booked');

      // Under-cost edit must be rejected (form re-renders, values unchanged).
      await page.goto(`/bookings/${booking.id}/edit/`);
      await page.getByLabel('Total amount').fill('107000.00');
      await page.getByLabel('Advance paid').fill('12000.00');
      await page.getByRole('button', { name: 'Update' }).click();
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/edit/$`));
      await expect(page.getByText('Please correct the errors below.')).toBeVisible();
      b = await getBooking(request, booking.id);
      expect(b.total_amount).toBe('110000.00');

      // Under-deposit edit must be rejected.
      await page.goto(`/bookings/${booking.id}/edit/`);
      await page.getByLabel('Total amount').fill('110000.00');
      await page.getByLabel('Advance paid').fill('5000.00');
      await page.getByRole('button', { name: 'Update' }).click();
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/edit/$`));
      await expect(page.getByText('Please correct the errors below.')).toBeVisible();
      b = await getBooking(request, booking.id);
      expect(b.advance_paid).toBe('12000.00');
    });

    test('BOOK-HP-05 — Cancel blocked while verified payments exist; after reversal releases plot', async ({
      page,
      request,
    }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      // Blocked while the verified advance payment exists.
      await page.goto(`/bookings/${booking.id}/cancel/`);
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));
      let b = await getBooking(request, booking.id);
      expect(b.status).toBe('pending');
      expect((await getPlot(request, f.plotId)).status).toBe('booked');

      // Reverse the advance payment, then cancel.
      const pays = await getPayments(request, booking.id);
      const verified = pays.find((p) => p.status === 'verified');
      expect(verified).toBeTruthy();
      await reversePayment(request, token, verified.id);

      await page.goto(`/bookings/${booking.id}/cancel/`);
      await page.getByRole('button', { name: /Confirm Cancellation/ }).click();
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

      b = await getBooking(request, booking.id);
      expect(b.status).toBe('cancelled');
      expect((await getPlot(request, f.plotId)).status).toBe('available');
      const audit = await (await request.get('/api/audit-logs/?action=cancel&model=Booking')).json() as any[];
      expect(audit.some((a) => a.object_id === booking.booking_id)).toBeTruthy();
    });

    test('BOOK-HP-06 — Reopen a cancelled booking returns it to pending and re-reserves the plot', async ({
      page,
      request,
    }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      const pays = await getPayments(request, booking.id);
      await reversePayment(request, token, pays.find((p) => p.status === 'verified').id);
      await cancelBookingWeb(request, token, booking.id);
      expect((await getBooking(request, booking.id)).status).toBe('cancelled');

      await page.goto(`/bookings/${booking.id}/reopen/`);
      await page.getByRole('button', { name: /Reopen Booking/ }).click();
      await expect(page).toHaveURL(new RegExp(`/bookings/${booking.id}/$`));

      expect((await getBooking(request, booking.id)).status).toBe('pending');
      expect((await getPlot(request, f.plotId)).status).toBe('reserved');
    });
  });

  test.describe('installments + invoice (data-plane)', () => {
    test('BOOK-HP-07 — Installment plan auto-generate: 12 monthly installments', async ({ request }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      const res = await request.post('/api/installment-plans/', {
        data: {
          booking: booking.id,
          total_installments: 12,
          installment_amount: '8166.67',
          down_payment_amount: '0',
          start_date: '2026-02-01',
          frequency: 'monthly',
          due_day: 1,
        },
        headers: csrf(token),
      });
      expect(res.status()).toBe(201);
      const plan = await res.json();
      expect(plan.installments.length).toBe(12);
      expect(plan.is_active).toBe(true);
      for (let i = 0; i < 12; i++) {
        expect(plan.installments[i].installment_number).toBe(i + 1);
        expect(Number(plan.installments[i].amount)).toBeGreaterThan(0);
      }
      expect(plan.installments[0].due_date).toBe('2026-03-01');
      expect(plan.installments[1].due_date).toBe('2026-04-01');
      expect(plan.installments[11].due_date).toBe('2027-02-01');
    });

    test('BOOK-HP-08 — Installment plan auto-generate: quarterly frequency', async ({ request }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      const res = await request.post('/api/installment-plans/', {
        data: {
          booking: booking.id,
          total_installments: 4,
          installment_amount: '24500.00',
          down_payment_amount: '0',
          start_date: '2026-02-01',
          frequency: 'quarterly',
          due_day: 1,
        },
        headers: csrf(token),
      });
      expect(res.status()).toBe(201);
      const plan = await res.json();
      expect(plan.installments.length).toBe(4);
      expect(plan.installments[0].due_date).toBe('2026-05-01');
      expect(plan.installments[1].due_date).toBe('2026-08-01');
      expect(plan.installments[2].due_date).toBe('2026-11-01');
      expect(plan.installments[3].due_date).toBe('2027-02-01');
    });

    test('BOOK-HP-10 — Installment plan auto-generate: due_day clamped to 28', async ({ request }) => {
      const token = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, token);
      const booking = await createBookingViaApi(request, token, f);

      const res = await request.post('/api/installment-plans/', {
        data: {
          booking: booking.id,
          total_installments: 3,
          installment_amount: '30000.00',
          down_payment_amount: '0',
          start_date: '2026-02-01',
          frequency: 'monthly',
          due_day: 31,
        },
        headers: csrf(token),
      });
      expect(res.status()).toBe(201);
      const plan = await res.json();
      // auto_generate clamps day(31) → 28 for every due date.
      expect(plan.installments[0].due_date).toBe('2026-03-28');
      expect(plan.installments[1].due_date).toBe('2026-04-28');
    });

    test('BOOK-HP-11 — Invoice PDF: accounts allowed, sales denied', async ({ request }) => {
      const adminToken = await apiLogin(request, 'admin');
      const f = await createBaseFixture(request, adminToken);
      const booking = await createBookingViaApi(request, adminToken, f);

      // accounts (finance) → PDF
      const accountsCtx = await apiRequest.newContext({ baseURL: BASE });
      try {
        await apiLogin(accountsCtx, 'accounts');
        const res = await accountsCtx.get(`/bookings/${booking.id}/invoice/`);
        expect(res.status()).toBe(200);
        expect(res.headers()['content-type']).toContain('application/pdf');
      } finally {
        await accountsCtx.dispose();
      }

      // sales → redirected to dashboard (no PDF)
      const salesCtx = await apiRequest.newContext({ baseURL: BASE });
      try {
        await apiLogin(salesCtx, 'sales');
        const res = await salesCtx.get(`/bookings/${booking.id}/invoice/`, { maxRedirects: 0 });
        expect(res.status()).toBe(302);
        expect(res.headers()['location']).toContain('/dashboard/');
      } finally {
        await salesCtx.dispose();
      }
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════════════
// EC — edge cases / boundaries
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('EC — edge cases / boundaries', () => {
  test('BOOK-EC-01 — Reopen conflict: plot re-sold → two active bookings', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F5 (core/views.py:1307 sets plot reserved
    // unconditionally, no active-booking check) — assert the CORRECT behaviour.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);

    const b1 = await createBookingViaApi(request, token, f);
    await reversePayment(request, token, (await getPayments(request, b1.id)).find((p) => p.status === 'verified').id);
    await cancelBookingWeb(request, token, b1.id);
    expect((await getBooking(request, b1.id)).status).toBe('cancelled');

    // Re-book the released plot.
    const b2 = await createBookingViaApi(request, token, f);

    // Reopen b1 (web-only).
    await request.post(`/bookings/${b1.id}/reopen/`, { form: {}, headers: csrf(token) });

    // Correct: the plot still has exactly one active booking (b2), and its status stays booked.
    const active = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[])
      .filter((b) => b.plot_number === f.plotNumber && ['pending', 'confirmed', 'active'].includes(b.status));
    expect(active.length).toBe(1);
    expect((await getPlot(request, f.plotId)).status).toBe('booked');
  });

  test('BOOK-EC-02 — Double-create: API validates plot availability (web path lacks select_for_update)', async ({
    request,
  }) => {
    // Soft note: the API create guards plot availability (assert the safe path); the WEB
    // booking_create_view has no select_for_update, so a true double-create race is only
    // reachable via two parallel UI submits (timing-dependent, not deterministic here).
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    await createBookingViaApi(request, token, f); // plot now booked

    const res = await request.post('/api/bookings/', {
      data: { customer: f.customerId, plot: f.plotId, total_amount: TOTAL_COST, advance_paid: ADVANCE, source: 'walk_in' },
      headers: csrf(token),
    });
    expect(res.status()).toBe(400);
    const bookings = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[])
      .filter((b) => b.plot_number === f.plotNumber);
    expect(bookings.length).toBe(1);
  });

  test('BOOK-EC-03 — Cancel with advance_paid > 0 but no verified payment row', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md — cancel only counts *verified* payments,
    // so a booking whose advance was reversed (but advance_paid re-set) is cancellable while
    // it still feeds revenue. Assert the CORRECT behaviour (cancel must be blocked).
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const pays = await getPayments(request, booking.id);
    await reversePayment(request, token, pays.find((p) => p.status === 'verified').id);
    // Restore advance_paid without re-creating a payment (BookingSerializer has no upper/verify guard).
    await request.patch(`/api/bookings/${booking.id}/`, { data: { advance_paid: ADVANCE }, headers: csrf(token) });

    await cancelBookingWeb(request, token, booking.id);

    const b = await getBooking(request, booking.id);
    expect(b.status).toBe('pending'); // correct: blocked
    expect((await getPlot(request, f.plotId)).status).toBe('booked'); // correct: still booked
  });

  test('BOOK-EC-04 — Zero installment_amount → auto_generate IntegrityError/500', async ({ request }) => {
    // BUG (spec §BOOK-EC-04): installment_amount is not validated; auto_generate creates
    // Installment(amount=0) → violates amount__gt=0 → 500. Assert the CORRECT 400.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const res = await request.post('/api/installment-plans/', {
      data: {
        booking: booking.id,
        total_installments: 12,
        installment_amount: '0',
        down_payment_amount: '0',
        start_date: '2026-02-01',
        frequency: 'monthly',
      },
      headers: csrf(token),
    });
    expect(res.status()).toBe(400);
  });

  test('BOOK-EC-05 — payment_progress / remaining_balance unclamped', async ({ request }) => {
    // BUG (spec §BOOK-EC-05): remaining_balance can go negative and payment_progress exceeds
    // 100 (no advance <= total constraint). Assert the CORRECT clamping.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    await request.patch(`/api/bookings/${booking.id}/`, { data: { advance_paid: '120000.00' }, headers: csrf(token) });

    const b = await getBooking(request, booking.id);
    expect(Number(b.remaining_balance)).toBeGreaterThanOrEqual(0);
    expect(b.payment_progress).toBeLessThanOrEqual(100);
  });

  test('BOOK-EC-06 — Transfer view 500 on non-numeric transfer_fee', async ({ request }) => {
    // BUG (spec §BOOK-EC-06): Decimal('abc') raises InvalidOperation → unhandled 500.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);
    const other = await createCustomer(request, token);

    const res = await request.post(`/bookings/${booking.id}/transfer/`, {
      form: { to_customer: String(other), transfer_fee: 'abc' },
      headers: csrf(token),
    });
    expect(res.status()).toBe(200); // correct: re-render with error (actual: 500)
  });

  test('BOOK-EC-07 — Transfer page renders no form fields (undefined form in context)', async ({ page, request }) => {
    // BUG (spec §BOOK-EC-07): booking_transfer_view passes no `form`; the template loop is empty.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    await page.goto(`/bookings/${booking.id}/transfer/`);
    await expect(page.getByRole('button', { name: /Transfer Booking/ })).toBeVisible();
    // Correct: a target-customer select should exist.
    await expect(page.locator('select[name="to_customer"], input[name="to_customer"]')).toHaveCount(1);
  });

  test('BOOK-EC-08 — booking_detail.html references non-existent completed_date/cancelled_date', async ({
    page,
    request,
  }) => {
    // BUG (spec §BOOK-EC-08): template uses {{ booking.cancelled_date }} (not a field) → blank date.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);
    await reversePayment(request, token, (await getPayments(request, booking.id)).find((p) => p.status === 'verified').id);
    await cancelBookingWeb(request, token, booking.id);

    await page.goto(`/bookings/${booking.id}/`);
    await page.getByRole('button', { name: /Timeline/ }).click();
    const item = page.locator('.timeline-item', { hasText: 'Booking Cancelled' });
    await expect(item).toBeVisible();
    // Correct: the cancellation timeline shows its date.
    await expect(item.locator('.timeline-date')).toContainText(/\d{1,2}\s+\w{3}\s+\d{4}/);
  });

  test('BOOK-EC-09 — InstallmentPlan due_day not validated on model/serializer', async ({ request }) => {
    // BUG (spec §BOOK-EC-09): API accepts due_day=31 (only the web form clamps 1–28).
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const res = await request.post('/api/installment-plans/', {
      data: {
        booking: booking.id,
        total_installments: 3,
        installment_amount: '30000.00',
        down_payment_amount: '0',
        start_date: '2026-02-01',
        frequency: 'monthly',
        due_day: 31,
      },
      headers: csrf(token),
    });
    expect(res.status()).toBe(400); // correct: reject due_day=31 (actual: 201)
  });

  test('BOOK-EC-10 — recalculate() rounding → zero installment amount', async ({ request }) => {
    // BUG (spec §BOOK-EC-10): base=(target/n).quantize('0.01') → 0.00 for tiny balances → IntegrityError.
    const token = await apiLogin(request, 'admin');
    const projectId = await createProject(request, token);
    const plot = await createPlot(request, token, projectId, { price: '10000.00', holdingDeposit: '0' });
    const customerId = await createCustomer(request, token);
    const res = await request.post('/api/bookings/', {
      data: { customer: customerId, plot: plot.id, total_amount: '10000.00', advance_paid: '9999.90', source: 'walk_in' },
      headers: csrf(token),
    });
    expect(res.status()).toBe(201);
    const booking = (await (await request.get(`/api/bookings/?project=${projectId}`)).json() as any[])
      .find((b) => b.plot_number === plot.plotNumber);
    created.bookings.push(booking.id);

    const planRes = await request.post('/api/installment-plans/', {
      data: {
        booking: booking.id,
        total_installments: 30,
        installment_amount: '0.01',
        down_payment_amount: '0',
        start_date: '2026-02-01',
        frequency: 'monthly',
      },
      headers: csrf(token),
    });
    expect(planRes.status()).toBe(201);
    const plan = await planRes.json();
    const first = plan.installments[0];

    const markRes = await request.post(`/api/installments/${first.id}/mark_paid/`, {
      data: { paid_amount: '0.01' },
      headers: csrf(token),
    });
    // Correct: mark-paid + recalculate must not 500 and every installment must remain > 0.
    expect(markRes.status()).toBe(200);
    const updatedPlan = await getPlanByBooking(request, booking.id);
    for (const inst of updatedPlan.installments) {
      expect(Number(inst.amount)).toBeGreaterThan(0);
    }
  });

  test('BOOK-EC-11 — Transfer to the same customer via forged POST (web)', async ({ request }) => {
    // BUG (spec §BOOK-EC-11): web view trusts POST to_customer and records a no-op transfer.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    await request.post(`/bookings/${booking.id}/transfer/`, {
      form: { to_customer: String(f.customerId), transfer_fee: '0' },
      headers: csrf(token),
    });

    const transfers = await (await request.get('/api/booking-transfers/')).json() as any[];
    expect(transfers.filter((t) => t.booking === booking.id && t.from_customer === t.to_customer).length).toBe(0);
  });

  test('BOOK-EC-12 — booking_id reuse after deleting the highest ID', async ({ request }) => {
    // BUG (spec §BOOK-EC-12): suffix parser reads last row, so deleting the highest id reuses it.
    const token = await apiLogin(request, 'admin');
    const p1 = await createProject(request, token);
    const plot1 = await createPlot(request, token, p1, { price: '10000.00', holdingDeposit: '0' });
    const customerId = await createCustomer(request, token);

    async function mkBooking(plotId: number, plotNumber: string): Promise<any> {
      const r = await request.post('/api/bookings/', {
        data: { customer: customerId, plot: plotId, total_amount: '10000.00', advance_paid: '0', source: 'walk_in' },
        headers: csrf(token),
      });
      expect(r.status()).toBe(201);
      const b = (await (await request.get(`/api/bookings/?project=${p1}`)).json() as any[])
        .find((x) => x.plot_number === plotNumber);
      created.bookings.push(b.id);
      return b;
    }

    const b1 = await mkBooking(plot1.id, plot1.plotNumber);
    const plot2 = await createPlot(request, token, p1, { price: '10000.00', holdingDeposit: '0' });
    const b2 = await mkBooking(plot2.id, plot2.plotNumber);

    // Delete the highest booking (no payments, so API delete succeeds).
    await request.delete(`/api/bookings/${b2.id}/`, { headers: csrf(token) });

    const plot3 = await createPlot(request, token, p1, { price: '10000.00', holdingDeposit: '0' });
    const b3 = await mkBooking(plot3.id, plot3.plotNumber);
    // Correct: a fresh, never-reused id.
    expect(b3.booking_id).not.toBe(b2.booking_id);
  });

  test('BOOK-EC-13 — amount_paid understates when verified payments < advance_paid', async ({ request }) => {
    // BUG (spec §BOOK-EC-13): amount_paid returns verified-sum (2000) instead of advance (10000).
    // amount_paid is a model property with no API/UI surface, so assert the observable
    // precondition (verified < advance) that triggers the understatement.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const p1 = (await getPayments(request, booking.id)).find((p) => p.status === 'verified');
    await reversePayment(request, token, p1.id);
    await request.patch(`/api/bookings/${booking.id}/`, { data: { advance_paid: ADVANCE }, headers: csrf(token) });

    // Add a verified payment of 2000 without going through the verify action (which bumps advance).
    const pr = await request.post('/api/payments/', {
      data: {
        booking: booking.id,
        amount: '2000.00',
        payment_date: new Date().toISOString().slice(0, 10),
        payment_method: 'cash',
        payment_type: 'installment',
      },
      headers: csrf(token),
    });
    expect(pr.status()).toBe(201);
    const p2 = await pr.json();
    await request.patch(`/api/payments/${p2.id}/`, { data: { status: 'verified' }, headers: csrf(token) });

    const verified = (await getPayments(request, booking.id)).filter((p) => p.status === 'verified');
    const verifiedSum = verified.reduce((s, p) => s + Number(p.amount), 0);
    const b = await getBooking(request, booking.id);
    // Observable precondition for the amount_paid bug.
    expect(verifiedSum).toBeLessThan(Number(b.advance_paid));
    expect(Number(b.advance_paid)).toBe(10000);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════════
// SEC — negative & security (auth / authorization / IDOR)
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('SEC — negative & security', () => {
  test('BOOK-SEC-01 — IDOR: booking list reachable by portal customer', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3 (views are @login_required only).
    const token = await apiLogin(request, 'admin');
    await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      await apiLogin(customerCtx, 'customer');
      const res = await customerCtx.get('/bookings/', { maxRedirects: 0 });
      expect(res.status()).toBe(302); // correct: deny (actual: 200 list)
    } finally {
      await customerCtx.dispose();
    }
  });

  test('BOOK-SEC-02 — IDOR: booking detail leaks amounts/notes/phone', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3.
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token), {
      notes: `PII note ${uid('pii')}`,
    });

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      await apiLogin(customerCtx, 'customer');
      const res = await customerCtx.get(`/bookings/${booking.id}/`, { maxRedirects: 0 });
      expect(res.status()).toBe(302); // correct: deny (actual: 200)
    } finally {
      await customerCtx.dispose();
    }
  });

  test('BOOK-SEC-03 — IDOR: booking edit lets customer change any booking amounts', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      const custToken = await apiLogin(customerCtx, 'customer');
      await customerCtx.post(`/bookings/${booking.id}/edit/`, {
        form: {
          customer: String(f.customerId),
          plot: String(f.plotId),
          total_amount: '110000.00',
          advance_paid: '12000.00',
          source: 'walk_in',
        },
        headers: csrf(custToken),
      });
    } finally {
      await customerCtx.dispose();
    }

    const b = await getBooking(request, booking.id);
    expect(b.total_amount).toBe(TOTAL_COST); // correct: unchanged (actual: 110000.00)
  });

  test('BOOK-SEC-04 — IDOR: booking create reachable by portal customer', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const availPlot = await createPlot(request, token, f.projectId);

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      const custToken = await apiLogin(customerCtx, 'customer');
      await customerCtx.post('/bookings/create/', {
        form: {
          customer: String(f.customerId),
          plot: String(availPlot.id),
          total_amount: TOTAL_COST,
          advance_paid: ADVANCE,
          source: 'walk_in',
        },
        headers: csrf(custToken),
      });
    } finally {
      await customerCtx.dispose();
    }

    const bookings = (await (await request.get(`/api/bookings/?project=${f.projectId}`)).json() as any[])
      .filter((b) => b.plot_number === availPlot.plotNumber);
    expect(bookings.length).toBe(0); // correct: denied (actual: booking created by customer)
  });

  test('BOOK-SEC-05 — API read-open: GET /api/bookings/ for any authenticated user', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3 (IsStaffOrAbove allows SAFE_METHODS for all).
    const token = await apiLogin(request, 'admin');
    await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      await apiLogin(customerCtx, 'customer');
      const res = await customerCtx.get('/api/bookings/');
      expect(res.status()).toBe(403); // correct: deny (actual: 200)
    } finally {
      await customerCtx.dispose();
    }
  });

  test('BOOK-SEC-06 — API read-open: booking detail + installments + reservations', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3 (has_object_permission true for non-DELETE).
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      await apiLogin(customerCtx, 'customer');
      expect((await customerCtx.get(`/api/bookings/${booking.id}/`)).status()).toBe(403);
      expect((await customerCtx.get('/api/installments/')).status()).toBe(403);
      expect((await customerCtx.get('/api/installment-plans/')).status()).toBe(403);
      expect((await customerCtx.get('/api/reservations/')).status()).toBe(403);
    } finally {
      await customerCtx.dispose();
    }
  });

  test('BOOK-SEC-07 — BookingSerializer update lacks total_cost / holding_deposit guards', async ({ request }) => {
    // BUG (spec §BOOK-SEC-07): plain BookingSerializer (update) only checks >0 / >=0 → under-sell accepted.
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const res = await request.patch(`/api/bookings/${booking.id}/`, {
      data: { total_amount: '100000.00', advance_paid: '5000.00' },
      headers: csrf(token),
    });
    expect(res.status()).toBe(400); // correct: reject (actual: 200)
  });

  test('BOOK-SEC-08 — Reservation.convert bypasses price guards (books at plot.price)', async ({ request }) => {
    // CODE-CONFIRMED BUG (spec §BOOK-SEC-08): convert uses total_amount=plot.price, ignoring
    // development/lease/other charges. Not reproducible via HTTP because the charge fields are
    // not writable through any API/form/admin surface (they default to 0), so price === total_cost
    // and the correct assertion holds; the under-sell requires a shell-seeded plot with charges.
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);

    const r = await request.post('/api/reservations/', {
      data: { customer: f.customerId, plot: f.plotId, token_amount: '10000.00', expires_at: new Date(Date.now() + 7 * 864e5).toISOString() },
      headers: csrf(token),
    });
    expect(r.status()).toBe(201);
    const reservation = await r.json();
    created.reservations.push(reservation.id);

    const conv = await request.post(`/api/reservations/${reservation.id}/convert/`, { headers: csrf(token) });
    expect(conv.status()).toBe(201);
    const booking = await conv.json();
    created.bookings.push(booking.id);
    // Correct: booking total_amount must be >= plot total_cost.
    expect(Number(booking.total_amount)).toBeGreaterThanOrEqual(Number(TOTAL_COST));
  });
});

// ═══════════════════════════════════════════════════════════════════════════════════
// API — API contract
// ═══════════════════════════════════════════════════════════════════════════════════
test.describe('API — API contract', () => {
  test('BOOK-API-01 — POST /api/bookings/ create: plot booked + verified Payment + Receipt + BKG id', async ({
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    expect(booking.booking_id).toMatch(/^BKG-\d{5}$/);
    expect(booking.status).toBe('pending');
    expect((await getPlot(request, f.plotId)).status).toBe('booked');

    const pays = await getPayments(request, booking.id);
    const verified = pays.filter((p) => p.status === 'verified');
    expect(verified.length).toBe(1);
    expect(verified[0].amount).toBe(ADVANCE);
    const receipts = await (await request.get(`/api/receipts/?payment=${verified[0].id}`)).json();
    expect(receipts.length).toBe(1);
  });

  test('BOOK-API-02 — POST /api/bookings/ create: price guard rejects under-sell / under-deposit', async ({
    request,
  }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);

    const underSell = await request.post('/api/bookings/', {
      data: { customer: f.customerId, plot: f.plotId, total_amount: '107000.00', advance_paid: ADVANCE, source: 'walk_in' },
      headers: csrf(token),
    });
    expect(underSell.status()).toBe(400);

    const underDeposit = await request.post('/api/bookings/', {
      data: { customer: f.customerId, plot: f.plotId, total_amount: TOTAL_COST, advance_paid: '5000.00', source: 'walk_in' },
      headers: csrf(token),
    });
    expect(underDeposit.status()).toBe(400);

    const negative = await request.post('/api/bookings/', {
      data: { customer: f.customerId, plot: f.plotId, total_amount: TOTAL_COST, advance_paid: '-1.00', source: 'walk_in' },
      headers: csrf(token),
    });
    expect(negative.status()).toBe(400);
  });

  test('BOOK-API-03 — POST /api/bookings/{id}/confirm/ action', async ({ request }) => {
    const token = await apiLogin(request, 'admin');
    const f = await createBaseFixture(request, token);
    const booking = await createBookingViaApi(request, token, f);

    // advance_paid > 0 → confirm succeeds.
    const ok = await request.post(`/api/bookings/${booking.id}/confirm/`, { headers: csrf(token) });
    expect(ok.status()).toBe(200);
    expect((await getBooking(request, booking.id)).status).toBe('confirmed');

    // Already confirmed → idempotent success.
    const again = await request.post(`/api/bookings/${booking.id}/confirm/`, { headers: csrf(token) });
    expect(again.status()).toBe(200);

    // advance_paid = 0 → 400.
    const project2 = await createProject(request, token);
    const plot2 = await createPlot(request, token, project2, { price: '10000.00', holdingDeposit: '0' });
    const zeroRes = await request.post('/api/bookings/', {
      data: { customer: f.customerId, plot: plot2.id, total_amount: '10000.00', advance_paid: '0', source: 'walk_in' },
      headers: csrf(token),
    });
    expect(zeroRes.status()).toBe(201);
    const zeroBooking = (await (await request.get(`/api/bookings/?project=${project2}`)).json() as any[])
      .find((b) => b.plot_number === plot2.plotNumber);
    created.bookings.push(zeroBooking.id);
    expect((await request.post(`/api/bookings/${zeroBooking.id}/confirm/`, { headers: csrf(token) })).status()).toBe(400);
  });

  test('BOOK-API-04 — POST /api/bookings/{id}/cancel/ action (blocked while verified payments exist)', async ({
    request,
  }) => {
    const token = await apiLogin(request, 'admin');

    // With verified payment → 400, plot stays booked.
    const f1 = await createBaseFixture(request, token);
    const b1 = await createBookingViaApi(request, token, f1);
    expect((await request.post(`/api/bookings/${b1.id}/cancel/`, { headers: csrf(token) })).status()).toBe(400);
    expect((await getBooking(request, b1.id)).status).toBe('pending');
    expect((await getPlot(request, f1.plotId)).status).toBe('booked');

    // No verified payment → success, plot released.
    const f2 = await createBaseFixture(request, token);
    const b2 = await createBookingViaApi(request, token, f2);
    await reversePayment(request, token, (await getPayments(request, b2.id)).find((p) => p.status === 'verified').id);
    const ok = await request.post(`/api/bookings/${b2.id}/cancel/`, { headers: csrf(token) });
    expect(ok.status()).toBe(200);
    expect((await getBooking(request, b2.id)).status).toBe('cancelled');
    expect((await getPlot(request, f2.plotId)).status).toBe('available');
  });

  test('BOOK-API-05 — Reopen is web-only (no /api/bookings/{id}/reopen/ endpoint)', async ({ request }) => {
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token));
    const res = await request.post(`/api/bookings/${booking.id}/reopen/`, { headers: csrf(token) });
    expect([404, 405]).toContain(res.status());
  });

  test('BOOK-API-06 — GET /api/bookings/ read-open (any authenticated user)', async ({ request }) => {
    // CONFIRMED BUG: docs/qa/findings-confirmed.md F3.
    const token = await apiLogin(request, 'admin');
    await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const customerCtx = await apiRequest.newContext({ baseURL: BASE });
    try {
      await apiLogin(customerCtx, 'customer');
      expect((await customerCtx.get('/api/bookings/')).status()).toBe(403); // correct: deny (actual: 200)
    } finally {
      await customerCtx.dispose();
    }
  });

  test('BOOK-API-07 — PATCH /api/bookings/{id}/ guard gap (below-cost / under-deposit accepted)', async ({
    request,
  }) => {
    // BUG (spec §BOOK-SEC-07/API-07): plain serializer does not re-apply total_cost/holding_deposit guards.
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const res = await request.patch(`/api/bookings/${booking.id}/`, {
      data: { total_amount: '100000.00', advance_paid: '5000.00' },
      headers: csrf(token),
    });
    expect(res.status()).toBe(400); // correct: reject (actual: 200)
  });

  test('BOOK-API-08 — GET /api/bookings/{id}/payment_summary/ float precision', async ({ request }) => {
    // BUG (spec §BOOK-API-08): payment_summary casts money through float() → loses exact Decimal form.
    const token = await apiLogin(request, 'admin');
    const booking = await createBookingViaApi(request, token, await createBaseFixture(request, token));

    const res = await request.get(`/api/bookings/${booking.id}/payment_summary/`);
    expect(res.status()).toBe(200);
    const body = await res.json();
    // Correct: exact Decimal strings ("108000.00"/"10000.00"). Actual: float() → numbers (108000 / 10000).
    expect(body.property_price).toBe(TOTAL_COST);
    expect(body.total_paid).toBe(ADVANCE);
  });
});
