# Generated by Django 6.0.7 on 2026-09-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customernominee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customernominee",
            name="nominee_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
