# Generated by Django 6.0.7 on 2026-09-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customernominee_nominee_name"),
        ("finance", "0007_voucherauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account_head",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared receivable control head this customer is linked to once mature.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="finance.accounthead",
            ),
        ),
    ]
