# Generated by Django 6.0.7 on 2026-08-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant Chat"),
                            ("lead_score", "Lead Scoring"),
                            ("property_description", "Property Description"),
                            ("reminder_draft", "Reminder Draft"),
                            ("insights", "Business Insights"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("disabled", "Disabled"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Interaction Log",
                "verbose_name_plural": "AI Interaction Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feature", "status"],
                        name="ai_aiintera_feature_91cf59_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_aiintera_created_63cae3_idx"
                    ),
                ],
            },
        ),
    ]
