# Generated by Django 6.0.7 on 2026-08-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinteractionlog",
            name="feature",
            field=models.CharField(
                choices=[
                    ("assistant", "Assistant Chat"),
                    ("lead_score", "Lead Scoring"),
                    ("property_description", "Property Description"),
                    ("reminder_draft", "Reminder Draft"),
                    ("insights", "Business Insights"),
                    ("hr_assistant", "HR Assistant Chat"),
                    ("leave_review", "Leave Review"),
                    ("payroll_insights", "Payroll Insights"),
                    ("attendance_insights", "Attendance Insights"),
                    ("job_description", "Job Description"),
                ],
                max_length=30,
            ),
        ),
    ]
