# Generated by Django 6.0.7 on 2026-08-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("core", "0007_agent_companysettings_leadnote_lead_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="core.agent",
            ),
        ),
    ]
