# Generated by Django 6.0.7 on 2026-08-25 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_agent"),
        ("core", "0009_companysettings_ai_language"),
        ("customers", "0004_customernominee"),
        ("properties", "0004_projectmilestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gt", 0)),
                name="booking_total_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("advance_paid__gte", 0)),
                name="booking_advance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="installment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", 0)),
                name="installment_paid_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_amount__gt", 0)),
                name="reservation_token_positive",
            ),
        ),
    ]
