"""
Django settings for samana_erp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the repo's .env file (gitignored).
# This is what makes DJANGO_SECRET_KEY, DB_*, EMAIL_*, SENDPK_*, DEEPSEEK_*
# configuration from .env actually take effect in both dev and production.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # python-dotenv is optional; without it, env vars must come from the OS.
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety. Set DJANGO_DEBUG=True locally for development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG:
    # Local development always needs loopback access regardless of .env.
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + ['localhost', '127.0.0.1', 'testserver']))

# HTTPS behind the Caddy reverse proxy — required for CSRF + secure cookies.
# Caddy terminates TLS and forwards X-Forwarded-Proto=https to the web container.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h]
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'rest_framework',
    'core',
    'customers',
    'properties',
    'bookings',
    'payments',
    'expenses',
    'notifications',
    'finance',
    'hr',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'samana_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_theme_processor',
                'core.context_processors.erp_context',
                'core.context_processors.company_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'samana_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Uses PostgreSQL when DB_ENGINE=postgres (production), otherwise SQLite (dev).
if os.environ.get('DB_ENGINE', 'sqlite') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'samana'),
            'USER': os.environ.get('DB_USER', 'samana'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Pakistan Standard Time (Samana Builders operates in PKT)
TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# In development AND during the test run `collectstatic` has not been run, so
# the manifest storage backend would raise "Missing staticfiles manifest entry"
# for every {% static %} tag. Use plain storage until we deploy.
# Set STATICFILES_MANIFEST=1 to force the manifest backend (used to build
# staticfiles.json via `collectstatic` before deploying).
_RUNNING_TESTS = 'test' in [arg.lower() for arg in __import__('sys').argv]
_MANIFEST_EXISTS = (BASE_DIR / 'staticfiles' / 'staticfiles.json').exists()
_FORCE_MANIFEST = os.environ.get('STATICFILES_MANIFEST', '0').lower() in ('1', 'true', 'yes')
if DEBUG or _RUNNING_TESTS or (not _MANIFEST_EXISTS and not _FORCE_MANIFEST):
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# CORS: allows the React dev server (5173) to talk to the Django API.
# Same-origin requests (single-server build) do not need CORS.
# Restrict in production via CORS_ALLOWED_ORIGINS env var (comma-separated).
_cors_origins = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOW_ALL_ORIGINS = not _cors_origins
CORS_ALLOWED_ORIGINS = _cors_origins
CORS_ALLOW_CREDENTIALS = True

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Email Configuration
# Toggle for email notifications. Set EMAIL_ENABLED=true to enable.
EMAIL_ENABLED = os.environ.get('EMAIL_ENABLED', 'False').lower() in ('1', 'true', 'yes')

# SMTP settings (Brevo / Sendinblue / etc.) — supplied via environment variables.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')

if EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Samana Builders <noreply@samanabuilders.com>')

# WhatsApp Configuration
WHATSAPP_PHONE_NUMBER = '+923001234567'  # Company WhatsApp number
WHATSAPP_API_URL = 'https://graph.facebook.com/v17.0/YOUR_PHONE_ID/messages'
WHATSAPP_API_TOKEN = ''  # Add your WhatsApp Business API token

# SMS Configuration (SendPK) — supplied via environment variables.
SENDPK_ENABLED = os.environ.get('SENDPK_ENABLED', 'False').lower() in ('1', 'true', 'yes')
SENDPK_API_KEY = os.environ.get('SENDPK_API_KEY', '')
# "SMS Alert" is SendPK's pre-approved shared/semi-branded sender (instant approval).
# Switch to "SAMANA" once the branded mask is PTA-approved on the account.
SENDPK_SENDER_ID = os.environ.get('SENDPK_SENDER_ID', 'SMS Alert')
SENDPK_BASE_URL = os.environ.get('SENDPK_BASE_URL', 'https://sendpk.com/api/sms.php')

# ─── DeepSeek AI (LangChain) ──────────────────────────────────────────────
# AI assistant features are powered by DeepSeek's chat models through the
# langchain-deepseek integration (OpenAI-compatible API).
AI_ENABLED = os.environ.get('AI_ENABLED', 'False').lower() in ('1', 'true', 'yes')
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-chat')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
