# Generated by Django 6.0.7 on 2026-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="provider_message_id",
            field=models.CharField(
                blank=True,
                help_text="Gateway message/delivery ID (e.g. SendPK messageid)",
                max_length=50,
            ),
        ),
    ]
