# Generated by Django 6.0.7 on 2026-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_provider_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("installment_reminder", "Installment Reminder"),
                    ("overdue_payment", "Overdue Payment"),
                    ("payment_confirmation", "Payment Confirmation"),
                    ("receipt_notification", "Receipt Notification"),
                    ("booking_notification", "Booking Notification"),
                    ("booking_approval", "Booking Approval"),
                    ("customer_welcome", "Customer Welcome"),
                    ("general", "General"),
                ],
                max_length=30,
            ),
        ),
    ]
